// Mocks generated by Mockito 5.4.6 from annotations
// in numbers_app/test/features/home/domain/usecases/get_random_number_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fpdart/fpdart.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:numbers_app/core/error/failure.dart' as _i5;
import 'package:numbers_app/features/domain/entities/number_entity.dart' as _i6;
import 'package:numbers_app/features/domain/repositories/number_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [NumberRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNumberRepository extends _i1.Mock implements _i2.NumberRepository {
  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.NumberEntity>> getRandomNumber() =>
      (super.noSuchMethod(
            Invocation.method(#getRandomNumber, []),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, _i6.NumberEntity>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, _i6.NumberEntity>>(
                    this,
                    Invocation.method(#getRandomNumber, []),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<_i4.Either<_i5.Failure, _i6.NumberEntity>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, _i6.NumberEntity>>(
                    this,
                    Invocation.method(#getRandomNumber, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i6.NumberEntity>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.NumberEntity>> getConcreteNumber({
    required int? number,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getConcreteNumber, [], {#number: number}),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, _i6.NumberEntity>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, _i6.NumberEntity>>(
                    this,
                    Invocation.method(#getConcreteNumber, [], {
                      #number: number,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<_i4.Either<_i5.Failure, _i6.NumberEntity>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, _i6.NumberEntity>>(
                    this,
                    Invocation.method(#getConcreteNumber, [], {
                      #number: number,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i6.NumberEntity>>);
}
